export const Media = [
    { label: "VINYL", value: 0 },
    { label: "CD", value: 1 }
];

export const Category = [
    { label: "NEW", value: false },
    { label: "USED", value: true },
];

export const ArtistGenre = [
    { label: "Rock", value: 0 },
    { label: "Pop", value: 1 },
    { label: "Jazz", value: 2 },
    { label: "Hiphop", value: 3 },
    { label: "Alternative", value: 4 },
    { label: "Classical", value: 5 },
    { label: "Francophone", value: 6 },
    { label: "Metal", value: 7 },
    { label: "Punk", value: 8 },
    { label: "Blues", value: 9 },
    { label: "World", value: 10 },
    { label: "Folk", value: 11 },
    { label: "Country", value: 12 },
    { label: "Soul", value: 13 },
    { label: "Funk", value: 14 },
    { label: "Electronica", value: 15 },
    { label: "Soundtrack", value: 16 },
];

export const AlbumGenre = [
    { label: "Rock", value: 0 },
    { label: "Pop", value: 1 },
    { label: "Jazz", value: 2 },
    { label: "Hiphop", value: 3 },
    { label: "Alternative", value: 4 },
    { label: "Classical", value: 5 },
    { label: "Francophone", value: 6 },
    { label: "Metal", value: 7 },
    { label: "Punk", value: 8 },
    { label: "Blues", value: 9 },
    { label: "World", value: 10 },
    { label: "Folk", value: 11 },
    { label: "Country", value: 12 },
    { label: "Soul", value: 13 },
    { label: "Funk", value: 14 },
    { label: "Electronica", value: 15 },
    { label: "Soundtrack", value: 16 },
    { label: "Hard", value: 17 },
    { label: "Fusion", value: 18 },
    { label: "Prog", value: 19 },
    { label: "Modal", value: 20 },
    { label: "Freejazz", value: 21 },
    { label: "Indie", value: 22 },
    { label: "Postbop", value: 23 },
    { label: "Minimalist", value: 24 },
    { label: "Psych", value: 25 },
    { label: "Hardrock", value: 26 },
    { label: "Rap", value: 27 },
    { label: "Garage", value: 28 },
    { label: "Vaporwave", value: 29 },
    { label: "Rockabilly", value: 30 },
    { label: "Experimental", value: 31 },
    { label: "Instrumental", value: 32 },
    { label: "Industrial", value: 33 },
    { label: "Synthwave", value: 34 },
    { label: "Kitsch", value: 35 },
    { label: "Reggae", value: 36 },
    { label: "Newwave", value: 37 },
    { label: "Downtempo", value: 38 },
    { label: "Acoustic", value: 39 },
    { label: "Newage", value: 40 },
    { label: "Opera", value: 41 },
    { label: "Stoner", value: 42 },
    { label: "Doom", value: 43 },
    { label: "Idm", value: 44 },
    { label: "Triphop", value: 45 },
    { label: "Deathcore", value: 46 },
    { label: "Deathmetal", value: 47 },
    { label: "Metalcore", value: 48 },
    { label: "Hardcore", value: 49 },
    { label: "Modern", value: 50 },
    { label: "House", value: 51 },
    { label: "Baroque", value: 52 },
    { label: "Romantic", value: 53 },
    { label: "Afrobeat", value: 54 },
    { label: "Dance", value: 55 },
    { label: "Noise", value: 56 },
    { label: "Ambient", value: 57 },
    { label: "Variety", value: 58 },
    { label: "Grunge", value: 59 },
    { label: "Historical", value: 60 },
    { label: "Musical", value: 61 },
    { label: "Disco", value: 62 },
    { label: "Comedy", value: 63 },
    { label: "Soundeffects", value: 64 },
    { label: "Kids", value: 65 },
    { label: "Christmas", value: 66 },
    { label: "Unspecified", value: 67 }
];

export const FormatType = {
    RPM_33: "RPM_33",
    RPM_45: "RPM_45",
    RPM_78: "RPM_78",
    LP: "LP",
    EP: "EP",
    ALBUM: "ALBUM",
    SINGLE: "SINGLE",
    DOUBLE: "DOUBLE",
    FLEXIDISC: "FLEXIDISC",
    PICTUREDISC: "PICTUREDISC",
    SHELLAC: "SHELLAC",
    DIGIPAK: "DIGIPAK",
    INCH_12: "INCH_12",
    INCH_10: "INCH_10",
    INCH_7: "INCH_7",
    INCH_5: "INCH_5",
    INCH_3: "INCH_3",
    UNSPECIFIED: "UNSPECIFIED"
};

export const Grade = [
    { label: "M", value: 0 },
    { label: "NM", value: 1 },
    { label: "VG_PLUS", value: 2 },
    { label: "VG", value: 3 },
    { label: "G_PLUS", value: 4 },
    { label: "G", value: 5 },
    { label: "F", value: 6 },
    { label: "P", value: 7 },
    { label: "NONE", value: 8 }
];

export const Province = [
    {label: "BC", value: "British Columbia"},
    {label: "AB", value: "Alberta"},
    {label: "SK", value: "Saskatchewan"},
    {label: "MB", value: "Manitoba"},
    {label: "ON", value: "Ontario"},
    {label: "QC", value: "Quebec"},
    {label: "NB", value: "New Brunswick"},
    {label: "NS", value: "Nova Scotia"},
    {label: "PE", value: "Prince Edward Island"},
    {label: "NL", value: "Newfoundland and Labrador"},
    {label: "YT", value: "Yukon"},
    {label: "NT", value: "Northwest Territories"},
    {label: "Nu", value: "Nunavut"},
    {label: "YT", value: "Yukon"}
];
